INSERT INTO CAR_DETAILS (NAME, TYPE, RENT_PER_DAY, TOTAL_QUANTITY)
VALUES ('Ford Fiesta', 'Compact', '20', '2');

INSERT INTO CAR_DETAILS (NAME, TYPE, RENT_PER_DAY, TOTAL_QUANTITY)
VALUES ('Ford Focus', 'Compact', '20', '2');

INSERT INTO CAR_DETAILS (NAME, TYPE, RENT_PER_DAY, TOTAL_QUANTITY)
VALUES ('Chevrolet Malibu', 'Full', '30', '2');

INSERT INTO CAR_DETAILS (NAME, TYPE, RENT_PER_DAY, TOTAL_QUANTITY)
VALUES ('Volkswagen Jetta', 'Full', '30', '2');

INSERT INTO CAR_DETAILS (NAME, TYPE, RENT_PER_DAY, TOTAL_QUANTITY)
VALUES ('Ford Egde', 'Large', '40', '2');

INSERT INTO CAR_DETAILS (NAME, TYPE, RENT_PER_DAY, TOTAL_QUANTITY)
VALUES ('Ford Escape', 'Large', '40', '2');

INSERT INTO CAR_DETAILS (NAME, TYPE, RENT_PER_DAY, TOTAL_QUANTITY)
VALUES ('BMW 328i', 'Luxury', '50', '2');

INSERT INTO CAR_DETAILS (NAME, TYPE, RENT_PER_DAY, TOTAL_QUANTITY)
VALUES ('BMW X5', 'Luxury', '50', '2');


INSERT INTO USER_DTL (NAME, EMAIL_ID, CAR_ID, START_DATE, END_DATE, TOTAL_COST)
VALUES ('ABC', 'abc@gmail.com', '2', '2018-05-24 15:05:12','2018-05-26 15:05:12', '40');

INSERT INTO USER_DTL (NAME, EMAIL_ID, CAR_ID, START_DATE, END_DATE, TOTAL_COST)
VALUES ('DEF', 'def@gmail.com', '3', '2018-05-24 15:05:12','2018-05-26 15:05:12', '60');

INSERT INTO USER_DTL (NAME, EMAIL_ID, CAR_ID, START_DATE, END_DATE, TOTAL_COST)
VALUES ('GHI', 'ghi@gmail.com', '2', '2018-05-24 15:05:12','2018-05-26 15:05:12', '40');

INSERT INTO USER_DTL (NAME, EMAIL_ID, CAR_ID, START_DATE, END_DATE, TOTAL_COST)
VALUES ('JKL', 'abc@gmail.com', '6', '2018-05-24 15:05:12','2018-05-26 15:05:12', '80');